pub fn convert_sdl_scancode(scancode: sdl2::keyboard::Scancode) -> bevy_input::keyboard::KeyCode {
    use bevy_input::keyboard::KeyCode as BevyKeyCode;
    use sdl2::keyboard::Scancode as SdlScancode;

    #[allow(unreachable_patterns)]
    match scancode {
        SdlScancode::A => BevyKeyCode::KeyA,
        SdlScancode::B => BevyKeyCode::KeyB,
        SdlScancode::C => BevyKeyCode::KeyC,
        SdlScancode::D => BevyKeyCode::KeyD,
        SdlScancode::E => BevyKeyCode::KeyE,
        SdlScancode::F => BevyKeyCode::KeyF,
        SdlScancode::G => BevyKeyCode::KeyG,
        SdlScancode::H => BevyKeyCode::KeyH,
        SdlScancode::I => BevyKeyCode::KeyI,
        SdlScancode::J => BevyKeyCode::KeyJ,
        SdlScancode::K => BevyKeyCode::KeyK,
        SdlScancode::L => BevyKeyCode::KeyL,
        SdlScancode::M => BevyKeyCode::KeyM,
        SdlScancode::N => BevyKeyCode::KeyN,
        SdlScancode::O => BevyKeyCode::KeyO,
        SdlScancode::P => BevyKeyCode::KeyP,
        SdlScancode::Q => BevyKeyCode::KeyQ,
        SdlScancode::R => BevyKeyCode::KeyR,
        SdlScancode::S => BevyKeyCode::KeyS,
        SdlScancode::T => BevyKeyCode::KeyT,
        SdlScancode::U => BevyKeyCode::KeyU,
        SdlScancode::V => BevyKeyCode::KeyV,
        SdlScancode::W => BevyKeyCode::KeyW,
        SdlScancode::X => BevyKeyCode::KeyX,
        SdlScancode::Y => BevyKeyCode::KeyY,
        SdlScancode::Z => BevyKeyCode::KeyZ,

        SdlScancode::Num1 => BevyKeyCode::Digit1,
        SdlScancode::Num2 => BevyKeyCode::Digit2,
        SdlScancode::Num3 => BevyKeyCode::Digit3,
        SdlScancode::Num4 => BevyKeyCode::Digit4,
        SdlScancode::Num5 => BevyKeyCode::Digit5,
        SdlScancode::Num6 => BevyKeyCode::Digit6,
        SdlScancode::Num7 => BevyKeyCode::Digit7,
        SdlScancode::Num8 => BevyKeyCode::Digit8,
        SdlScancode::Num9 => BevyKeyCode::Digit9,
        SdlScancode::Num0 => BevyKeyCode::Digit0,

        SdlScancode::Return => BevyKeyCode::Enter,
        SdlScancode::Escape => BevyKeyCode::Escape,
        SdlScancode::Backspace => BevyKeyCode::Backspace,
        SdlScancode::Tab => BevyKeyCode::Tab,
        SdlScancode::Space => BevyKeyCode::Space,
        SdlScancode::Minus => todo!(),
        SdlScancode::Equals => todo!(),
        SdlScancode::LeftBracket => todo!(),
        SdlScancode::RightBracket => todo!(),
        SdlScancode::Backslash => todo!(),
        SdlScancode::NonUsHash => todo!(),
        SdlScancode::Semicolon => todo!(),
        SdlScancode::Apostrophe => todo!(),
        SdlScancode::Grave => todo!(),
        SdlScancode::Comma => todo!(),
        SdlScancode::Period => todo!(),
        SdlScancode::Slash => todo!(),
        SdlScancode::CapsLock => todo!(),
        SdlScancode::F1 => todo!(),
        SdlScancode::F2 => todo!(),
        SdlScancode::F3 => todo!(),
        SdlScancode::F4 => todo!(),
        SdlScancode::F5 => todo!(),
        SdlScancode::F6 => todo!(),
        SdlScancode::F7 => todo!(),
        SdlScancode::F8 => todo!(),
        SdlScancode::F9 => todo!(),
        SdlScancode::F10 => todo!(),
        SdlScancode::F11 => todo!(),
        SdlScancode::F12 => todo!(),
        SdlScancode::PrintScreen => todo!(),
        SdlScancode::ScrollLock => todo!(),
        SdlScancode::Pause => todo!(),
        SdlScancode::Insert => todo!(),
        SdlScancode::Home => todo!(),
        SdlScancode::PageUp => todo!(),
        SdlScancode::Delete => todo!(),
        SdlScancode::End => todo!(),
        SdlScancode::PageDown => todo!(),
        SdlScancode::Right => BevyKeyCode::ArrowRight,
        SdlScancode::Left => BevyKeyCode::ArrowLeft,
        SdlScancode::Down => BevyKeyCode::ArrowDown,
        SdlScancode::Up => BevyKeyCode::ArrowUp,
        SdlScancode::NumLockClear => todo!(),
        SdlScancode::KpDivide => todo!(),
        SdlScancode::KpMultiply => todo!(),
        SdlScancode::KpMinus => todo!(),
        SdlScancode::KpPlus => todo!(),
        SdlScancode::KpEnter => todo!(),
        SdlScancode::KpPeriod => todo!(),
        SdlScancode::NonUsBackslash => todo!(),
        SdlScancode::Application => todo!(),
        SdlScancode::Power => todo!(),
        SdlScancode::KpEquals => todo!(),
        SdlScancode::F13 => todo!(),
        SdlScancode::F14 => todo!(),
        SdlScancode::F15 => todo!(),
        SdlScancode::F16 => todo!(),
        SdlScancode::F17 => todo!(),
        SdlScancode::F18 => todo!(),
        SdlScancode::F19 => todo!(),
        SdlScancode::F20 => todo!(),
        SdlScancode::F21 => todo!(),
        SdlScancode::F22 => todo!(),
        SdlScancode::F23 => todo!(),
        SdlScancode::F24 => todo!(),
        SdlScancode::Execute => todo!(),
        SdlScancode::Help => todo!(),
        SdlScancode::Menu => todo!(),
        SdlScancode::Select => todo!(),
        SdlScancode::Stop => todo!(),
        SdlScancode::Again => todo!(),
        SdlScancode::Undo => todo!(),
        SdlScancode::Cut => todo!(),
        SdlScancode::Copy => todo!(),
        SdlScancode::Paste => todo!(),
        SdlScancode::Find => todo!(),
        SdlScancode::Mute => todo!(),
        SdlScancode::VolumeUp => todo!(),
        SdlScancode::VolumeDown => todo!(),
        SdlScancode::KpComma => todo!(),
        SdlScancode::KpEqualsAS400 => todo!(),
        SdlScancode::International1 => todo!(),
        SdlScancode::International2 => todo!(),
        SdlScancode::International3 => todo!(),
        SdlScancode::International4 => todo!(),
        SdlScancode::International5 => todo!(),
        SdlScancode::International6 => todo!(),
        SdlScancode::International7 => todo!(),
        SdlScancode::International8 => todo!(),
        SdlScancode::International9 => todo!(),
        SdlScancode::Lang1 => todo!(),
        SdlScancode::Lang2 => todo!(),
        SdlScancode::Lang3 => todo!(),
        SdlScancode::Lang4 => todo!(),
        SdlScancode::Lang5 => todo!(),
        SdlScancode::Lang6 => todo!(),
        SdlScancode::Lang7 => todo!(),
        SdlScancode::Lang8 => todo!(),
        SdlScancode::Lang9 => todo!(),
        SdlScancode::AltErase => todo!(),
        SdlScancode::SysReq => todo!(),
        SdlScancode::Cancel => todo!(),
        SdlScancode::Clear => todo!(),
        SdlScancode::Prior => todo!(),
        SdlScancode::Return2 => todo!(),
        SdlScancode::Separator => todo!(),
        SdlScancode::Out => todo!(),
        SdlScancode::Oper => todo!(),
        SdlScancode::ClearAgain => todo!(),
        SdlScancode::CrSel => todo!(),
        SdlScancode::ExSel => todo!(),
        SdlScancode::Kp00 => todo!(),
        SdlScancode::Kp000 => todo!(),
        SdlScancode::ThousandsSeparator => todo!(),
        SdlScancode::DecimalSeparator => todo!(),
        SdlScancode::CurrencyUnit => todo!(),
        SdlScancode::CurrencySubUnit => todo!(),
        SdlScancode::KpLeftParen => todo!(),
        SdlScancode::KpRightParen => todo!(),
        SdlScancode::KpLeftBrace => todo!(),
        SdlScancode::KpRightBrace => todo!(),
        SdlScancode::KpTab => todo!(),
        SdlScancode::KpBackspace => todo!(),
        SdlScancode::KpA => todo!(),
        SdlScancode::KpB => todo!(),
        SdlScancode::KpC => todo!(),
        SdlScancode::KpD => todo!(),
        SdlScancode::KpE => todo!(),
        SdlScancode::KpF => todo!(),
        SdlScancode::KpXor => todo!(),
        SdlScancode::KpPower => todo!(),
        SdlScancode::KpPercent => todo!(),
        SdlScancode::KpLess => todo!(),
        SdlScancode::KpGreater => todo!(),
        SdlScancode::KpAmpersand => todo!(),
        SdlScancode::KpDblAmpersand => todo!(),
        SdlScancode::KpVerticalBar => todo!(),
        SdlScancode::KpDblVerticalBar => todo!(),
        SdlScancode::KpColon => todo!(),
        SdlScancode::KpHash => todo!(),
        SdlScancode::KpSpace => todo!(),
        SdlScancode::KpAt => todo!(),
        SdlScancode::KpExclam => todo!(),
        SdlScancode::KpMemStore => todo!(),
        SdlScancode::KpMemRecall => todo!(),
        SdlScancode::KpMemClear => todo!(),
        SdlScancode::KpMemAdd => todo!(),
        SdlScancode::KpMemSubtract => todo!(),
        SdlScancode::KpMemMultiply => todo!(),
        SdlScancode::KpMemDivide => todo!(),
        SdlScancode::KpPlusMinus => todo!(),
        SdlScancode::KpClear => todo!(),
        SdlScancode::KpClearEntry => todo!(),
        SdlScancode::KpBinary => todo!(),
        SdlScancode::KpOctal => todo!(),
        SdlScancode::KpDecimal => todo!(),
        SdlScancode::KpHexadecimal => todo!(),
        SdlScancode::LCtrl => todo!(),
        SdlScancode::LShift => todo!(),
        SdlScancode::LAlt => todo!(),
        SdlScancode::LGui => todo!(),
        SdlScancode::RCtrl => todo!(),
        SdlScancode::RShift => todo!(),
        SdlScancode::RAlt => todo!(),
        SdlScancode::RGui => todo!(),
        SdlScancode::Mode => todo!(),
        SdlScancode::AudioNext => todo!(),
        SdlScancode::AudioPrev => todo!(),
        SdlScancode::AudioStop => todo!(),
        SdlScancode::AudioPlay => todo!(),
        SdlScancode::AudioMute => todo!(),
        SdlScancode::MediaSelect => todo!(),
        SdlScancode::Www => todo!(),
        SdlScancode::Mail => todo!(),
        SdlScancode::Calculator => todo!(),
        SdlScancode::Computer => todo!(),
        SdlScancode::AcSearch => todo!(),
        SdlScancode::AcHome => todo!(),
        SdlScancode::AcBack => todo!(),
        SdlScancode::AcForward => todo!(),
        SdlScancode::AcStop => todo!(),
        SdlScancode::AcRefresh => todo!(),
        SdlScancode::AcBookmarks => todo!(),
        SdlScancode::BrightnessDown => todo!(),
        SdlScancode::BrightnessUp => todo!(),
        SdlScancode::DisplaySwitch => todo!(),
        SdlScancode::KbdIllumToggle => todo!(),
        SdlScancode::KbdIllumDown => todo!(),
        SdlScancode::KbdIllumUp => todo!(),
        SdlScancode::Eject => todo!(),
        SdlScancode::Sleep => todo!(),
        SdlScancode::App1 => todo!(),
        SdlScancode::App2 => todo!(),
        SdlScancode::Num => todo!(),
        SdlScancode::Kp1 => todo!(),
        SdlScancode::Kp2 => todo!(),
        SdlScancode::Kp3 => todo!(),
        SdlScancode::Kp4 => todo!(),
        SdlScancode::Kp5 => todo!(),
        SdlScancode::Kp6 => todo!(),
        SdlScancode::Kp7 => todo!(),
        SdlScancode::Kp8 => todo!(),
        SdlScancode::Kp9 => todo!(),
        SdlScancode::Kp0 => todo!(),
        SdlScancode::Return => todo!(),
        SdlScancode::Escape => todo!(),
        SdlScancode::Backspace => todo!(),
        SdlScancode::Tab => todo!(),
        SdlScancode::Space => todo!(),
        SdlScancode::Minus => todo!(),
        SdlScancode::Equals => todo!(),
        SdlScancode::LeftBracket => todo!(),
        SdlScancode::RightBracket => todo!(),
        SdlScancode::Backslash => todo!(),
        SdlScancode::NonUsHash => todo!(),
        SdlScancode::Semicolon => todo!(),
        SdlScancode::Apostrophe => todo!(),
        SdlScancode::Grave => todo!(),
        SdlScancode::Comma => todo!(),
        SdlScancode::Period => todo!(),
        SdlScancode::Slash => todo!(),
        SdlScancode::CapsLock => todo!(),
        SdlScancode::F1 => todo!(),
        SdlScancode::F2 => todo!(),
        SdlScancode::F3 => todo!(),
        SdlScancode::F4 => todo!(),
        SdlScancode::F5 => todo!(),
        SdlScancode::F6 => todo!(),
        SdlScancode::F7 => todo!(),
        SdlScancode::F8 => todo!(),
        SdlScancode::F9 => todo!(),
        SdlScancode::F10 => todo!(),
        SdlScancode::F11 => todo!(),
        SdlScancode::F12 => todo!(),
        SdlScancode::PrintScreen => todo!(),
        SdlScancode::ScrollLock => todo!(),
        SdlScancode::Pause => todo!(),
        SdlScancode::Insert => todo!(),
        SdlScancode::Home => todo!(),
        SdlScancode::PageUp => todo!(),
        SdlScancode::Delete => todo!(),
        SdlScancode::End => todo!(),
        SdlScancode::PageDown => todo!(),
        SdlScancode::Right => todo!(),
        SdlScancode::Left => todo!(),
        SdlScancode::Down => todo!(),
        SdlScancode::Up => todo!(),
        SdlScancode::NumLockClear => todo!(),
        SdlScancode::KpDivide => todo!(),
        SdlScancode::KpMultiply => todo!(),
        SdlScancode::KpMinus => todo!(),
        SdlScancode::KpPlus => todo!(),
        SdlScancode::KpEnter => todo!(),
        SdlScancode::KpPeriod => todo!(),
        SdlScancode::NonUsBackslash => todo!(),
        SdlScancode::Application => todo!(),
        SdlScancode::Power => todo!(),
        SdlScancode::KpEquals => todo!(),
        SdlScancode::F13 => todo!(),
        SdlScancode::F14 => todo!(),
        SdlScancode::F15 => todo!(),
        SdlScancode::F16 => todo!(),
        SdlScancode::F17 => todo!(),
        SdlScancode::F18 => todo!(),
        SdlScancode::F19 => todo!(),
        SdlScancode::F20 => todo!(),
        SdlScancode::F21 => todo!(),
        SdlScancode::F22 => todo!(),
        SdlScancode::F23 => todo!(),
        SdlScancode::F24 => todo!(),
        SdlScancode::Execute => todo!(),
        SdlScancode::Help => todo!(),
        SdlScancode::Menu => todo!(),
        SdlScancode::Select => todo!(),
        SdlScancode::Stop => todo!(),
        SdlScancode::Again => todo!(),
        SdlScancode::Undo => todo!(),
        SdlScancode::Cut => todo!(),
        SdlScancode::Copy => todo!(),
        SdlScancode::Paste => todo!(),
        SdlScancode::Find => todo!(),
        SdlScancode::Mute => todo!(),
        SdlScancode::VolumeUp => todo!(),
        SdlScancode::VolumeDown => todo!(),
        SdlScancode::KpComma => todo!(),
        SdlScancode::KpEqualsAS400 => todo!(),
        SdlScancode::International1 => todo!(),
        SdlScancode::International2 => todo!(),
        SdlScancode::International3 => todo!(),
        SdlScancode::International4 => todo!(),
        SdlScancode::International5 => todo!(),
        SdlScancode::International6 => todo!(),
        SdlScancode::International7 => todo!(),
        SdlScancode::International8 => todo!(),
        SdlScancode::International9 => todo!(),
        SdlScancode::Lang1 => todo!(),
        SdlScancode::Lang2 => todo!(),
        SdlScancode::Lang3 => todo!(),
        SdlScancode::Lang4 => todo!(),
        SdlScancode::Lang5 => todo!(),
        SdlScancode::Lang6 => todo!(),
        SdlScancode::Lang7 => todo!(),
        SdlScancode::Lang8 => todo!(),
        SdlScancode::Lang9 => todo!(),
        SdlScancode::AltErase => todo!(),
        SdlScancode::SysReq => todo!(),
        SdlScancode::Cancel => todo!(),
        SdlScancode::Clear => todo!(),
        SdlScancode::Prior => todo!(),
        SdlScancode::Return2 => todo!(),
        SdlScancode::Separator => todo!(),
        SdlScancode::Out => todo!(),
        SdlScancode::Oper => todo!(),
        SdlScancode::ClearAgain => todo!(),
        SdlScancode::CrSel => todo!(),
        SdlScancode::ExSel => todo!(),
        SdlScancode::Kp00 => todo!(),
        SdlScancode::Kp000 => todo!(),
        SdlScancode::ThousandsSeparator => todo!(),
        SdlScancode::DecimalSeparator => todo!(),
        SdlScancode::CurrencyUnit => todo!(),
        SdlScancode::CurrencySubUnit => todo!(),
        SdlScancode::KpLeftParen => todo!(),
        SdlScancode::KpRightParen => todo!(),
        SdlScancode::KpLeftBrace => todo!(),
        SdlScancode::KpRightBrace => todo!(),
        SdlScancode::KpTab => todo!(),
        SdlScancode::KpBackspace => todo!(),
        SdlScancode::KpA => todo!(),
        SdlScancode::KpB => todo!(),
        SdlScancode::KpC => todo!(),
        SdlScancode::KpD => todo!(),
        SdlScancode::KpE => todo!(),
        SdlScancode::KpF => todo!(),
        SdlScancode::KpXor => todo!(),
        SdlScancode::KpPower => todo!(),
        SdlScancode::KpPercent => todo!(),
        SdlScancode::KpLess => todo!(),
        SdlScancode::KpGreater => todo!(),
        SdlScancode::KpAmpersand => todo!(),
        SdlScancode::KpDblAmpersand => todo!(),
        SdlScancode::KpVerticalBar => todo!(),
        SdlScancode::KpDblVerticalBar => todo!(),
        SdlScancode::KpColon => todo!(),
        SdlScancode::KpHash => todo!(),
        SdlScancode::KpSpace => todo!(),
        SdlScancode::KpAt => todo!(),
        SdlScancode::KpExclam => todo!(),
        SdlScancode::KpMemStore => todo!(),
        SdlScancode::KpMemRecall => todo!(),
        SdlScancode::KpMemClear => todo!(),
        SdlScancode::KpMemAdd => todo!(),
        SdlScancode::KpMemSubtract => todo!(),
        SdlScancode::KpMemMultiply => todo!(),
        SdlScancode::KpMemDivide => todo!(),
        SdlScancode::KpPlusMinus => todo!(),
        SdlScancode::KpClear => todo!(),
        SdlScancode::KpClearEntry => todo!(),
        SdlScancode::KpBinary => todo!(),
        SdlScancode::KpOctal => todo!(),
        SdlScancode::KpDecimal => todo!(),
        SdlScancode::KpHexadecimal => todo!(),
        SdlScancode::LCtrl => todo!(),
        SdlScancode::LShift => todo!(),
        SdlScancode::LAlt => todo!(),
        SdlScancode::LGui => todo!(),
        SdlScancode::RCtrl => todo!(),
        SdlScancode::RShift => todo!(),
        SdlScancode::RAlt => todo!(),
        SdlScancode::RGui => todo!(),
        SdlScancode::Mode => todo!(),
        SdlScancode::AudioNext => todo!(),
        SdlScancode::AudioPrev => todo!(),
        SdlScancode::AudioStop => todo!(),
        SdlScancode::AudioPlay => todo!(),
        SdlScancode::AudioMute => todo!(),
        SdlScancode::MediaSelect => todo!(),
        SdlScancode::Www => todo!(),
        SdlScancode::Mail => todo!(),
        SdlScancode::Calculator => todo!(),
        SdlScancode::Computer => todo!(),
        SdlScancode::AcSearch => todo!(),
        SdlScancode::AcHome => todo!(),
        SdlScancode::AcBack => todo!(),
        SdlScancode::AcForward => todo!(),
        SdlScancode::AcStop => todo!(),
        SdlScancode::AcRefresh => todo!(),
        SdlScancode::AcBookmarks => todo!(),
        SdlScancode::BrightnessDown => todo!(),
        SdlScancode::BrightnessUp => todo!(),
        SdlScancode::DisplaySwitch => todo!(),
        SdlScancode::KbdIllumToggle => todo!(),
        SdlScancode::KbdIllumDown => todo!(),
        SdlScancode::KbdIllumUp => todo!(),
        SdlScancode::Eject => todo!(),
        SdlScancode::Sleep => todo!(),
        SdlScancode::App1 => todo!(),
        SdlScancode::App2 => todo!(),
        SdlScancode::Num => todo!(),
    }
}

pub fn convert_sdl_keycode(keycode: sdl2::keyboard::Keycode) -> bevy_input::keyboard::Key {
    use bevy_input::keyboard::Key as BevyKey;
    use sdl2::keyboard::Keycode as SdlKeycode;

    #[allow(unreachable_patterns)]
    match keycode {
        SdlKeycode::BACKSPACE => BevyKey::Backspace,
        SdlKeycode::SPACE => BevyKey::Space,
        SdlKeycode::ESCAPE => BevyKey::Escape,
        SdlKeycode::TAB => BevyKey::Tab,

        SdlKeycode::Kp0
        | SdlKeycode::Kp1
        | SdlKeycode::Kp2
        | SdlKeycode::Kp3
        | SdlKeycode::Kp4
        | SdlKeycode::Kp5
        | SdlKeycode::Kp6
        | SdlKeycode::Kp7
        | SdlKeycode::Kp8
        | SdlKeycode::Kp9
        | SdlKeycode::Num1
        | SdlKeycode::Num2
        | SdlKeycode::Num3
        | SdlKeycode::Num4
        | SdlKeycode::Num5
        | SdlKeycode::Num6
        | SdlKeycode::Num7
        | SdlKeycode::Num8
        | SdlKeycode::Num9
        | SdlKeycode::Num0
        | SdlKeycode::A
        | SdlKeycode::B
        | SdlKeycode::C
        | SdlKeycode::D
        | SdlKeycode::E
        | SdlKeycode::F
        | SdlKeycode::G
        | SdlKeycode::H
        | SdlKeycode::I
        | SdlKeycode::J
        | SdlKeycode::K
        | SdlKeycode::L
        | SdlKeycode::M
        | SdlKeycode::N
        | SdlKeycode::O
        | SdlKeycode::P
        | SdlKeycode::Q
        | SdlKeycode::R
        | SdlKeycode::S
        | SdlKeycode::T
        | SdlKeycode::U
        | SdlKeycode::V
        | SdlKeycode::W
        | SdlKeycode::X
        | SdlKeycode::Y
        | SdlKeycode::Z => BevyKey::Character(keycode.name().into()),
        SdlKeycode::Up => BevyKey::ArrowUp,
        SdlKeycode::Down => BevyKey::ArrowDown,
        SdlKeycode::Left => BevyKey::ArrowLeft,
        SdlKeycode::Right => BevyKey::ArrowRight,

        _ => {
            unimplemented!("{keycode:?}: {}", keycode.name())
        }
    }
}
